ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class AboutUsController : Controller
    {
        //
        // GET: /AboutUs/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/ComingSoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ComingSoonController : Controller
    {
        //
        // GET: /ComingSoon/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/ComparisonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ComparisonsController : Controller
    {
        //
        // GET: /InfiniteInk/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Error(string errorMessage = "")
        {
            int code = 0;
            int.TryParse(errorMessage, out code);

            switch (code)
            {
                case 403:
                    return View("Error", "403 Forbidden");
                case 404:
                    return View("Error", "404 Page Not Found");
                case 500:
                    return View("Error", "500 Internal Server Error");
                default:
                    return View("Error");

            }
        }

        public ActionResult Test403()
        {
            return new HttpStatusCodeResult(403);
        }

        public ActionResult Test404()
        {
            return new HttpStatusCodeResult(404);
        }

        public ActionResult Test500()
        {
            return new HttpStatusCodeResult(500);
        }

        public ActionResult TestGeneralError()
        {
            return Error();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/InfiniteInkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ComparisonsController : Controller
    {
        //
        // GET: /InfiniteInk/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/InvestorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class InvestorsController : Controller
    {
        //
        // GET: /Investors/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClericoDezign_SquidInc.Controllers
{
    public class ShopController : Controller
    {
        //
        // GET: /Shop/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/AboutUs/Index.cshtml
@{
	ViewBag.Title = "Index";
}
@section customLogo{
		<img src="~/Content/img/logo_about.png" />
}

<script>
    document.getElementById("outlineBox").className = "aboutUsOutline";
</script>

<section class="SquidBody">
    <h3>Manamement Team</h3>
	<p>We here at Squid Inc. are going to revolutionize the printer industry. 
        We have developed a printer that does not use the standard ink many of the other 
        printers use. We have developed a system that allows our printers to make their 
        own ink out of the pollutants in the environment. This not only allows our 
        printers to be run free of the standard ink but also makes our printers the 
        most environment friendly printers on the market. </p>
    <p>
        Squid Inc. was founded in 2011 and was founded by Jamar Jones, Steve Razim, 
        and Alexander Lawson who share co-owner status along with equal shares of 
        stock in the company.
    </p>
    <div class="fullCEO">
        <div class="ceoPic">
            <img src="~/Content/img/021054h.jpg" />
        </div>
        <div class="ceoInfo">
            <h3>Jamar Jones</h3>
	        <p>I am the CEO of Squid Inc. I have run many successful businesses in the past and hope to continue that trend with this one. Under my leadership Squid Inc. has completed many new deals and bumped up our release schedule for our new printer by half a year.</p>
            <h4>Master’s in Business Administration from University of Chicago</h4>
        </div>
    </div>
    <div class="fullCEO">
        <div class="ceoPic">
            <img src="~/Content/img/053839f.jpg" />
        </div>
        <div class="ceoInfo">
            <h3>Huppert Oldberg</h3>
            <p>I am the CFO and the marketing specialist at Squid Inc. and part of my duties involve making sure our investors get the most out of their investment and I am the one who plans our marketing campaigns. When I worked at Bounce Co. I cut $2.3 million in wasteful spending and lead them to record profits. I hope to do the same here at Squid inc</p>
            <h4>BS in Technology Management—Neumont University (1998)</h4>
        </div>
    </div>
    <div class="fullCEO">
        <div class="ceoPic">
            <img src="~/Content/img/937592k.jpg" />
        </div>
        <div class="ceoInfo">
            <h3>Alexander Lawson</h3>
            <p>My name is Alexander Lawson and I am the product manager and head of human relations here at Squid Inc. My primary job outside of HR is to oversee production of our product and the implementation of prototypes as well as organizing workload between researching and engineering new parts. </p>
            <h4>BS in Psychology from University of Chicago Champaign—Urbana (2002)</h4>
        </div>
    </div>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/ComingSoon/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section customLogo{
    <img src="~/Content/img/logo_coming_soon.png" />
}

<script>
    document.getElementById("outlineBox").className = "comingSoonOutline";
    document.getElementById("innerBox").className = "comingSoonInline";
</script>

<section class="SquidBody">
    <img src="~/Content/img/comingsoon_with_b.png" class="comingSoonImage" />

    <article class="leftColumn">
        <div class="comingSoonCategory">
            <div class="comingSoonLeftText">
                <h3>Pens and Markers</h3>
                <ul>
                    <li>Pens</li>
                    <li>Markers</li>
                    <li>Multi-Color Markers</li>
                    <li>Highlights</li>
                    <li>Neon Markers</li>
                </ul>
            </div>
            <img src="~/Content/img/pen.jpg" alt="Infinite Ink Pen" class="comingSoonRightImage" />
        </div>

        <div class="comingSoonCategory">
            <div class="comingSoonRightText">
                <h3>Mini Keyboard</h3>
                <ul>
                    <li>Emergency Edits</li>
                    <li>Basic File Editing</li>
                </ul>
            </div>
            <img src="~/Content/img/mini keyboard.jpg" alt="Keyboard" class="comingSoonLeftImage" />
        </div>
    </article>

    <article class="rightColumn">
        <div class="comingSoonCategory">
            <div class="comingSoonLeftText">
                <h3>Color Ink</h3>
                <ul>
                    <li>Family colors</li>
                    <li>Neon colors</li>
                    <li>Exotic colrs</li>
                </ul>
            </div>
            <img src="~/Content/img/colorInk.jpg" alt="Color ink" class="comingSoonRightImage" />
        </div>

        <div class="comingSoonCategory">
            <div class="comingSoonRightText">
                <h3>Phone Docking</h3>
                <ul>
                    <li>Import from your phone</li>
                    <li>Print from your phone</li>
                    <li>Printing on the go</li>
                </ul>
            </div>
            <img src="~/Content/img/smartphonedock.jpg" alt="Smart phone dock" class="comingSoonLeftImage" />
        </div>
    </article>

    <article class="center">
        <div class="comingSoonCategory">
            <div class="comingSoonRightText">
                <h3>Image Editor</h3>
                <ul>
                    <li>Basic image editor</li>
                    <li>Touch screen</li>
                </ul>
            </div>
            <img src="~/Content/img/touch_screen.jpg" alt="Touch screen" class="comingSoonLeftImage" />
        </div>
    </article>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Comparisons/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_comparisons.png" />
}

<script>
    document.getElementById("outlineBox").className = "comparisonsOutline";
    document.getElementById("innerBox").className = "compareDataBody";
</script>



<section class="SquidBody">
	<img src="~/Content/img/prettyData.png" class="image comparisonImage"/>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Contact/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_contact.png" />
}

<script>
    document.getElementById("outlineBox").className = "homeOutline";
</script>

<section class="SquidBody">
	
	<!-- Form -->
	<form id="contact-form" action="/" method="post">
		<h3>Be Notified When We Launch!</h3>
		<h4>Fill out the form below, and we'll add you to our list, or if you have a question, we'll reply as soon as possible.</h4>
		<div>
			<label>
				<span>Name: (required)</span>
				<input placeholder="Please enter your name" type="text" tabindex="1" required autofocus>
			</label>
		</div>
		<div>
			<label>
				<span>Email: (required)</span>
				<input placeholder="Please enter your email address" type="email" tabindex="2" required>
			</label>
		</div>
		<div>
			<label>
				<span>Telephone: (required)</span>
				<input placeholder="Please enter your number" type="tel" tabindex="3" required>
			</label>
		</div>
		<div>
			<label>
				<span>Message: (required)</span>
				<textarea placeholder="Include all the details you can" tabindex="5" required></textarea>
			</label>
		</div>
		<div>
			<button name="submit" type="submit" id="contact-submit">Send Email</button>
		</div>
	</form>
	<!-- /Form -->

	<script src="js/scripts.js"></script>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section customLogo{
    <img src="~/Content/img/logo_home.png" />
}

@section AdditionalStyleSheets{
    <link rel="stylesheet" type="text/css" href="~/Content/css/WowSlider.css" media="screen" />
}

@section AdditionalScripts{
    <script type="text/javascript" src="~/Content/js/jquery.js"></script>
}

<script  type="text/javascript">
    document.getElementById("outlineBox").className = "homeOutline";
    document.getElementById("innerBox").className = "homeBody";

    function slideSwitch() {
        var $active = $('#slideshow IMG.active');
        var $caption = $('.blot1 IMG.activate');

        if ($active.length == 0) $active = $('#slideshow IMG:last');
        if ($caption.length == 0) $caption = $('.blot1 IMG:last');

        // use this to pull the images in the order they appear in the markup
        var $next = $active.next().length ? $active.next()
            : $('#slideshow IMG:first');

        var $nextOne = $caption.next().length ? $caption.next()
            : $('.blot1 IMG:first');

        $active.addClass('last-active');
        $caption.addClass('last-activate');

        $next.css({ opacity: 0.0 })
            .addClass('active')
            .animate({ opacity: 1.0 }, 1000, function () {
                $active.removeClass('active last-active');
            });

        $nextOne.css({ opacity: 0.0 })
            .addClass('activate')
            .animate({ opacity: 1.0 }, 1000, function () {
                $caption.removeClass('activate last-activate');
            });
    }

    $(function () {
        setInterval("slideSwitch()", 5000);
    });
</script>


<section class="SquidBody">
    <div class="tagLine">
        <img src="~/Content/img/tagline.png" />
    </div>
    <div id="slideshow">
        <img src="~/Content/img/a_2_o.jpg" alt="Slideshow Image 1" class="active" />
        <img src="~/Content/img/printers 2.jpg" alt="Slideshow Image 2" />
    </div>
    <div class="blot1">
        <img src="~/Content/img/inkBlotFirst.png" class="activate"/>
        <img src="~/Content/img/inkBlotSecond.png" />
    </div>

    <div class="blot2">
        <div class="homeInfo">
            Launching in summer of 2014 our revolutionary printer can save your business 
            thousands of dollars a year on printer ink alone. If you want to find out 
            more about our printer and how it works check our @Html.ActionLink("Products Page", "Index", "Product").  
            If you want to see how our printer compares to some of the highest rated 
            printers in the industry click @Html.ActionLink("here","Index", "Comparisons"). 
        </div>
    </div>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/InfiniteInk/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_infinite_ink.png" />
}

<script>
    document.getElementById("outlineBox").className = "infiniteInkOutline";
</script>

<section class="SquidBody">
	<h1>Generic Title</h1>
	<p>Generic text</p>
	<div class="spacing"></div>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Investors/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_invest.png" />
}

<script>
    document.getElementById("outlineBox").className = "investorOutline";
</script>

<section class="SquidBody">
    <h3 class="investHeading">Invest Your Money, Reap Infinitely!</h3>
    <img src="~/Content/img/business-woman-next-to-office-printer-16795393.jpg" class="investPic"/>
	<p class="investBody">We here at Squid Inc. appreciate that you are as confident in our future as we are.
         Since you have invested in the company we want to extend our thanks to by 
        offering you a part in our beta testing community. Our beta testing community is 
        what makes sure our products are fully functional and work as designed.
	</p>
    <img src="~/Content/img/man-receives-package-delivery-11754575.jpg" class="investPic"/>
    <p class="investBody">As a beta tester you will receive modules for the printer months in advance so 
        you can make sure that everything works and nothing brakes or messes with the 
        base printer. We do require something out of our beta testers we require that at 
        least three times during the beta that they fill out a report we send them so we 
        can see how the module is doing. If we do not receive the report three times 
        they will be taken off the list as a beta tester.
    </p>

    <p>After a certain amount of successful beta tests you will get complete modules and 
        products for free. This differs from the beta tests in the fact that with the 
        beta test you keep the beta model which may still be good but if you want the 
        retail model you will have to buy it. However after two successful beta tests 
        with submitting all the reports you need to, you have the ability to send the 
        beta module back and get the retail module for free
    </p>
    <img src="~/Content/img/Untitled.jpg" class="graph"/>
    <br />
    <br />

</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Product/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_products.png" />
}

<script>
    document.getElementById("outlineBox").className = "productsOutline";
</script>

<section class="SquidBody">
    <h3>Infinite Ink?</h3>
    <img src="~/Content/img/1.png" class="image productImage"/>
	<p>Our printers are run using ink that they make and store in specialized ink cartridges. Our printer uses small fans to pull air into filters that are made to filter out particulates in the air which are then deposited into the chemical bath that we use to separate the pigment which is used to create the ink. The ink is created from the pigments using a specialized enzymatic process to convert pigment to ink where the ink is then sent to the specialized ink cartridges.</p>
    <img src="~/Content/img/2.png" class="image productImage"/>
    <h3>Filter</h3>
    <p>Air is pulled through the filter using the fans to pull it into the filter, which then traps the necessary particles from the air and “traps” them in the filter. Instead of just catching particles from the air we trap those using synthetic catalysts. This ensures that we trap more material than if we did not use the synthetic catalysts and that the materials we trap are usable for the production of the ink</p>
    <h3>How the Ink is Made</h3>
    <img src="~/Content/img/3.png" class="image productImage"/>
    <p>After the material has been removed from the filter, it is sorted into pigments which is done using a chemical bath which uses specialized enzymes to ”pull” pigments one at a time until it is all separated. When this works is conjunction with the filter the only byproducts are clean air and usable ink. </p>
    <p>After the particulates are separated by pigment, each pigment is sent to a specific compartment where they are then converted to ink to be used by the printer. Every particle can be used to make many different colors of ink. However if you don’t have the module that lets you use some of the colors, the particles are then just made into the standard black ink. The ink is created through a biological process manipulating the amino acids and several forms of chemosynthetic reactions. Most of this technology is derived from many deep water organisms that produce their own ink which is where the name “Squid Inc.” came from.</p>
</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/Shop/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@section customLogo{
		<img src="~/Content/img/logo_shop.png" />
}

<script>
    document.getElementById("outlineBox").className = "shopOutline";
</script>

<section class="SquidBody">
	<article class="shopItem">
        <div>
            <img src="~/Content/img/epson_workforce_840_aio.png" class="image"/>
        </div>
        <h1>Eternal Ink Printer</h1>
        <h2>Infinite Ink!</h2> 
        <p>Never replace another cartidge again!</p>
        
        <div class="pricing">$249.99</div>
        <h3>Coming Summer 2014!</h3>
  	</article>

</section>

ClericoDezign_SquidInc/ClericoDezign_SquidInc/Views/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
    @RenderSection("AdditionalStyleSheets", false)
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker|Just+Another+Hand|Give+You+Glory|Wire+One|Pacifico|Rock+Salt' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
	@Scripts.Render("~/Content/js")
	@Scripts.Render("~/bundles/modernizr")
    @RenderSection("AdditionalScripts", false)
	<link rel="stylesheet" type="text/css" href="~/Style/Style.css" />

    <link rel="stylesheet" media="screen and (max-width: 1000px)" href="~/Style/1000.css" />
    <link rel="stylesheet" media="screen and (max-width: 800px)" href="~/Style/800.css" />
</head>
	<body>

		<nav>
			<div class="logoPlace">
				@RenderSection("customLogo")
			</div>
			<ul class="nav-stacked">
				<li>@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("Products", "Index", "Product", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("Comparisons", "Index", "Comparisons", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("Shop", "Index", "Shop", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("Invest", "Index", "Investors", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("About Us", "Index", "AboutUs", new { }, new { @class = "linkStyle" })</li>
				<li>@Html.ActionLink("Coming Soon", "Index", "ComingSoon", new { }, new { @class = "linkStyle" })</li>
			</ul>
		</nav>
		<div id="outlineBox">

			<div id="innerBox">
				@RenderBody()

				@Scripts.Render("~/bundles/jquery")
				@RenderSection("scripts", required: false)
			</div>

            <footer>
                <div class="footerTop">
                    <span class="contact">
                    @Html.ActionLink("Contact Us", "Index", "Contact")
                    </span> | 
                    <span class="social">
                    <a href="http://www.neumont.edu/"><i class="fa fa-facebook"></i></a>
                    <a href="http://www.neumont.edu/"><i class="fa fa-twitter"></i></a>
                    <a href="http://www.neumont.edu/"><i class="fa fa-google-plus"></i></a>
                    </span>
                </div>
                <div class="footerBottom">
                    <span class="copyright">&copy; Squid Inc. 2014
                    </span> | 
                    <span class="contact">Squid Inc.
                    25 E. South Temple, SLC, UT, 84111
                    (801)555-7173
                    </span>
                </div>
            </footer>

		</div>
	</body>
</html>